default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tnja_development

test:
  <<: *default
  database: tnja_test

production:
  <<: *default
  url: <%= ENV['DB_URL'] %>
